---
version: '3.7'

networks:
  xes-platform-network:
    name: xes-platform-network

services:
  node-crypto-forex-rates:
    build:
      .
    container_name: xes_node-crypto-forex-rates
    networks:
      - xes-platform-network
    restart: unless-stopped
    environment:
      PROXEUS_INSTANCE_URL: http://xes-platform:1323
      AUTH_KEY: secret
      SERVICE_URL: http://node-crypto-forex-rates:1323
      TZ: Europe/Zurich
    ports:
      - "8011:8011"
