---
version: '3.7'

networks:
  xes-platform-network:
    name: xes-platform-network

services:
  node-crypto-forex-rates:
    image: proxeus/node-crypto-forex-rates:latest
    container_name: xes_node-crypto-forex-rates
    networks:
      - xes-platform-network
    restart: unless-stopped
    environment:
      PROXEUS_INSTANCE_URL: http://xes-platform:1323
      SERVICE_SECRET: secret
      SERVICE_PORT: 8011
      SERVICE_URL: node-crypto-forex-rates
      TZ: Europe/Zurich
    ports:
      - "8011:8011"
